### ISSUE TITLE
triangular arbitrage

### ISSUE THREAD

**Issue by onthetunnel** [deanturpin/arbitrage#11]
hello can this project do triangular arbitrage on one exchange ? Thanks You!

**Comment by deanturpin** [comment]
Not at the moment but it's certainly something I'd like to explore!

https://en.wikipedia.org/wiki/Triangular_arbitrage

**Comment by onthetunnel** [comment]
Hello Thanks You for reply , if this project can do 24/7 auto triangular arbitrage on binance (low fee) , is best profit for btc ! Hope you can develop it,  Thanks You!
